// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DataAccess.Enities
{
    public partial class Address
    {
        public int Id { get; set; }
        public string Country { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public DateTime? Created { get; set; }
        public string CreatedById { get; set; }

        //public virtual ICollection<Institution> Institutions { get; set; }
    }
}