// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DataAccess.Enities
{
    public partial class Course
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int InstitutionId { get; set; }
        public string Code { get; set; }
        public DateTime? Created { get; set; }
        public string CreatedById { get; set; }
        public int SystemStatusId { get; set; }

        public virtual AspNetUser CreatedBy { get; set; }
        public virtual Institution Institution { get; set; }
    }
}