// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DataAccess.Enities
{
    public partial class Institution
    {
        public Institution()
        {
            AspNetUsers = new HashSet<AspNetUser>();
            Courses = new HashSet<Course>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public DateTime Created { get; set; }
        public int TypeId { get; set; }
        public int? AddressId { get; set; }
        public int? CountryId { get; set; }
        public string CreatedById { get; set; }
        public int SystemStatusId { get; set; }

        public virtual Address Address { get; set; }
        public virtual InstitutionType Type { get; set; }
        public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
        public virtual ICollection<Course> Courses { get; set; }
    }
}