// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DataAccess.Enities
{
    public partial class InstitutionType
    {

        public int Id { get; set; }
        public string Name { get; set; }
        public bool IsActive { get; set; }

        //public virtual ICollection<Institution> Institutions { get; set; }
    }
}