// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DataAccess.Enities
{
    public partial class Lab
    {
        public Lab()
        {
            Schedules = new HashSet<Schedule>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Token { get; set; }
        public DateTime? TokenExpiration { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? StopDate { get; set; }
        public int MaximumTime { get; set; }
        public int? InstitutionId { get; set; }
        public DateTime? Created { get; set; }
        public string CreatedById { get; set; }
        public int SystemStatusId { get; set; }
        public string Config { get; set; }
        public string Guid { get; set; }
        public string Description { get; set; }

        public virtual AspNetUser CreatedBy { get; set; }
        public virtual ICollection<Schedule> Schedules { get; set; }
    }
}