// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DataAccess.Enities
{
    public partial class Schedule
    {
        public long Id { get; set; }
        public string UserId { get; set; }
        public int LabId { get; set; }
        public DateTime StartTime { get; set; }
        public DateTime EndTime { get; set; }
        public int? StatusId { get; set; }
        public int SystemStatusId { get; set; }

        public virtual Lab Lab { get; set; }
        public virtual ScheduleStatus Status { get; set; }
        public virtual AspNetUser User { get; set; }
    }
}