// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace DataAccess.Enities
{
    public partial class StudentsLab
    {
        public string UserId { get; set; }
        public int LabId { get; set; }

        public virtual Lab Lab { get; set; }
        public virtual AspNetUser User { get; set; }
    }
}