//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUserDTO 
    {
        public string Id { get; set; }
        public string Email { get; set; }
        public Nullable<bool> EmailConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<bool> PhoneNumberConfirmed { get; set; }
        public Nullable<bool> TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public Nullable<bool> LockoutEnabled { get; set; }
        public Nullable<int> AccessFailedCount { get; set; }
        public string UserName { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<int> InstitutionId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<bool> CompletedRegistration { get; set; }
        public Nullable<int> SystemStatusId { get; set; }
        public Nullable<bool> IsCompletedRegistration { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    }
}
